# This is a basic workflow to help you get started with Actions

name: Daily Year Progress

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  schedule:
    - cron: '0 0 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 16.x
      - name: Generate charts
        run: |
          npm install
          node preprocess.js
      - name: Updated charts
        run: |
          git config --global user.name 'itsnikhil'
          git config --global user.email 'taneja.nikhil03@gmail.com@users.noreply.github.com'
          git add .
          git commit --allow-empty -m "Automated report"
          git push
      - name: Publish thread message
        env:
          INSTAGRAM_USERNAME: ${{ secrets.INSTAGRAM_USERNAME }}
          INSTAGRAM_PASSWORD: ${{ secrets.INSTAGRAM_PASSWORD }}
        run: |
          npm install
          node index.js
